### ISSUE TITLE
ERROR: invalid input syntax for integer: "00000000-0000-0000-0000-000000000000"

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#126] opened 2019-10-09 09:17 UTC
Hi, 
I get this error : 

Applying migration...
ERROR: invalid input syntax for integer: "00000000-0000-0000-0000-000000000000"
  Position: 39
Database migrated and script renamed to: applied-postgres-sql-migration-1570612445975.sql

when running java -jar dsl-clc.jar properties=simpeg.props
here is my props file:
dsl=./dsl
postgres=localhost/xxxx?user=xxx&password=xxxx
migration
apply
force

what should i do?

**Comment by zapov** [comment] 2019-10-09 11:05
You can open up SQL which was executing and locate the problematic line.
It's hard to say whats going on without actual DSL or SQL.

CLC allows you to pass in folder where sql files will be kept, otherwise it will be in the temp folder (you can see that if you enable log)

**Comment by araneta** [comment] 2019-12-01 15:12
what does Position: 39 mean? is it line number?

**Comment by araneta** [comment] 2019-12-01 15:32
and also this error:
ERROR: operator does not exist: character varying = integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 182
Database migrated and script renamed to: applied-postgres-sql-migration-1575214197628.sql

what does it mean? i can't find some error on line 182

**Comment by zapov** [comment] 2019-12-01 16:42
I actually released a new compiler which might fix that uuid to int cast issue.
But if the error persist, the best thing you can do is try to apply sql script part by part until you get to the problematic part.
That way you can isolate problem and report it back.
Those errors are PG messages about some problems in the script.

**Comment by araneta** [comment] 2019-12-01 23:15
Thanks I will try the new version. Btw why I can't find you framework on techempower.com/benchmarks/ anymore ?

**Comment by araneta** [comment] 2019-12-01 23:44
may be you should put this line to the generated sql
\set ON_ERROR_STOP on

I found the error: its from this dsl
	aggregate UnitOfWork(code){
		string code {unique;}
		string name;
		timestamp? createdAt;
		timestamp? updatedAt;
	}

its generate this sql which error

CREATE OR REPLACE FUNCTION "UnitOfWork"("simpeg"."Employment_entity") RETURNS "referx"."UnitOfWork_entity" AS $$
SELECT _r FROM "referx"."UnitOfWork_entity" _r WHERE _r."code" = $1."UnitOfWorkID"
$$ LANGUAGE SQL;

**Comment by araneta** [comment] 2019-12-02 00:59
psql:/tmp/DSL-Platform/simpeg-iain/postgres-sql-migration-1575247707506.sql:36336: ERROR:  invalid input syntax for integer: "00000000-0000-0000-0000-000000000000"
LINE 1: UPDATE "simpeg"."Address" SET "ID" = '00000000-0000-0000-000...
and the dsl is 
aggregate Address(ID){
		guid ID;
		string? street;
		string? dusun;
		string? RT;
		string? RW;
		string? village;
		Area? *subdistrict;
		Area? *city;
		Area? *province;
		string? postalCode;
		string? phoneNo;
		string? contactNo;	
		
		timestamp? createdAt;
		timestamp? updatedAt;	
		string? mediaIDs;
	}

i already set the ID to guid but why it does not updated
simak=# \d+ simpeg."Address";
                                                                  Table "simpeg.Address"
    Column     |           Type           | Collation | Nullable |                   Default                    | Storage  | Stats target |  Description
---------------+--------------------------+-----------+----------+----------------------------------------------+----------+--------------+---------------
 ID            | integer                  |           | not null | nextval('simpeg."Address_ID_seq"'::regclass) | plain    |              | NGS generated
 street        | character varying        |           |          |                                              | extended |              | NGS generated
 dusun         | character varying        |           |          |                                              | extended |              | NGS generated
 RT            | character varying        |           |          |                                              | extended |              | NGS generated
 RW            | character varying        |           |          |                                              | extended |              | NGS generated
 village       | character varying        |           |          |                                              | extended |              | NGS generated
 subdistrictID | character varying(8)     |           |          |                                              | extended |              | NGS generated
 cityID        | character varying(8)     |           |          |                                              | extended |              | NGS generated
 provinceID    | character varying(8)     |           |          |                                              | extended |              | NGS generated
 postalCode    | character varying        |           |          |                                              | extended |              | NGS generated
 phoneNo       | character varying        |           |          |                                              | extended |              | NGS generated
 contactNo     | character varying        |           |          |                                              | extended |              | NGS generated
 createdAt     | timestamp with time zone |           |          |                                              | plain    |              | NGS generated
 updatedAt     | timestamp with time zone |           |          |                                              | plain    |              | NGS generated
 mediaIDs      | character varying        |           |          |                                              | extended |              | NGS generated

**Comment by zapov** [comment] 2019-12-02 07:01
This migration scripts should always be run within a transaction. So they should either fail or succeed in full. Thus, no need for on error stop, because it should be the default behavior.

If you've been running them outside of transaction you will have a hard time resolving your type problems.

There should be ALTER TABLE with a type change before this update, although the query should not really look like this but rather should change it via using statement.

Things you can try to resolve the issue:
 1) create the migration for an empty DB - to check if the model applies cleanly
 2) have a DB copy and manually apply part by part of the diff migration - check that it does the expected changes (alter table alter column ID type UUID and similar things)

If you can isolate the migration problem you can post the DSL here, but I doubt there is some problem in the migrations (although its of course a possibility). In that case please make a reproducible from a minimal dsl: previous dsl - currently applied to the DB, new dsl - which will create problematic diff migration

As for techempower, the framework is still there, they just released a build without the revenj for reasons only known to them. But it's not represented as it should be due to many bad decisions/changes they made along the way... and I don't really have the time to fix it for them

**Comment by araneta** [comment] 2019-12-03 03:04
it seems that the migration script can not modify primary key if its already have some datas

**Closed** 2019-12-04 05:00 UTC
